// postinstall.js — generated by @camera.ui/cli
const { platform, arch } = require('os');
const { existsSync, copyFileSync, mkdirSync, chmodSync } = require('fs');
const { join, dirname } = require('path');

const os = platform();
const a = arch();
const goArch = a === 'x64' ? 'amd64' : a;
const goos = os === 'win32' ? 'windows' : os;
const ext = os === 'win32' ? '.exe' : '';

const pkg = require('./package.json');
const pluginName = pkg.name.replace(/^@[^/]+\//, '');
const scope = pkg.name.includes('/') ? pkg.name.split('/')[0] : undefined;
const platformPkgName = scope ? scope + '/' + pluginName + '-' + goos + '-' + goArch : pluginName + '-' + goos + '-' + goArch;

let binarySource;
try {
  const pkgDir = dirname(require.resolve(platformPkgName + '/package.json'));
  binarySource = join(pkgDir, pluginName + ext);
} catch {
  process.exit(0); // Platform package not installed — skip silently
}

if (!existsSync(binarySource)) process.exit(0);

const binDir = join(__dirname, 'dist', 'bin');
mkdirSync(binDir, { recursive: true });
const target = join(binDir, 'plugin' + ext);
copyFileSync(binarySource, target);
try {
  chmodSync(target, 0o755);
} catch {
  // Ignore chmod errors on platforms that don't support it (e.g. Windows)
}
