// postinstall.js — generated by @camera.ui/cli
const { platform, arch } = require('os');
const { existsSync, copyFileSync, mkdirSync, chmodSync, readFileSync } = require('fs');
const { join, dirname } = require('path');

const os = platform();
const a = arch();
// Map Node's arch/platform names back to Go's so the right platform package
// resolves. Most match; the exceptions are x64->amd64 and mipsel->mipsle.
const goArch = a === 'x64' ? 'amd64' : a === 'mipsel' ? 'mipsle' : a;
const goos = os === 'win32' ? 'windows' : os; // 'freebsd' matches as-is
const ext = os === 'win32' ? '.exe' : '';

// On Linux, glibc and musl builds ship as separate platform packages (the musl
// one carries a `-musl` suffix). Detect musl so the matching binary is chosen —
// a glibc binary can't exec on Alpine/musl and vice versa.
function isMusl() {
  if (os !== 'linux') return false;
  // 1) The process report lists the runtime's shared objects + glibc version.
  try {
    if (process.report && typeof process.report.getReport === 'function') {
      process.report.excludeNetwork = true;
      const rep = process.report.getReport();
      if (rep && rep.header && rep.header.glibcVersionRuntime) return false;
      if (rep && Array.isArray(rep.sharedObjects) && rep.sharedObjects.some((f) => f.includes('libc.musl-') || f.includes('ld-musl-'))) {
        return true;
      }
    }
  } catch {
    // fall through to the ldd-based checks
  }
  // 2) The dynamic loader on musl systems references musl.
  try {
    if (readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')) return true;
  } catch {
    // /usr/bin/ldd may not exist — try invoking ldd directly
  }
  // 3) Last resort: ask ldd for its version banner.
  try {
    if (require('child_process').execSync('ldd --version 2>&1', { encoding: 'utf-8' }).includes('musl')) return true;
  } catch {
    // give up — assume glibc
  }
  return false;
}

const key = goos + '-' + goArch + (isMusl() ? '-musl' : '');

const pkg = require('./package.json');
const pluginName = pkg.name.replace(/^@[^/]+\//, '');
const scope = pkg.name.includes('/') ? pkg.name.split('/')[0] : undefined;
const platformPkgName = scope ? scope + '/' + pluginName + '-' + key : pluginName + '-' + key;

let binarySource;
try {
  const pkgDir = dirname(require.resolve(platformPkgName + '/package.json'));
  binarySource = join(pkgDir, pluginName + ext);
} catch {
  // The matching platform package isn't installed. Either this platform isn't
  // supported, or npm skipped the optional dependency (a known npm bug:
  // https://github.com/npm/cli/issues/4828). Warn but don't fail the install.
  console.warn(
    '[' +
    pluginName +
    '] no native binary for ' +
    key +
    ' (expected package ' +
    platformPkgName +
    ').\n' +
    '  If your platform should be supported, remove node_modules + package-lock.json and reinstall.',
  );
  process.exit(0);
}

if (!existsSync(binarySource)) process.exit(0);

const binDir = join(__dirname, 'dist', 'bin');
mkdirSync(binDir, { recursive: true });
const target = join(binDir, 'plugin' + ext);
copyFileSync(binarySource, target);
try {
  chmodSync(target, 0o755);
} catch {
  // Ignore chmod errors on platforms that don't support it (e.g. Windows)
}
